### ISSUE TITLE
Bug - You can create or update an event with a blank "" event override status

### ISSUE THREAD

**Issue by mikethetike** [big-neon/bn-api#772] opened 2018-12-18 10:44 UTC

**Comment by philipr-za** [comment] 2018-12-18 15:36
I cannot reproduce this, if I try make or update an event with an explicit blank override_status field I get the validator response of what the possible values are.

**Comment by philipr-za** [comment] 2018-12-18 16:03
Fixed by https://github.com/big-neon/bn-api/pull/727

**Closed** 2018-12-18 16:03 UTC
Labels: Urgent, current sprint, question
