### ISSUE TITLE
A user should be able to easily indicate that they are interested in an event

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-api#158] opened 2018-08-24 21:47 UTC
child of big-neon/docs#23

A user should be able to easily indicate that they are interested in an event so that they can receive to be not notified when the events status changes to On Sale, the event is almost sold out, or when another friend buys a ticket or expresses interest

**Comment by Timo614** [comment] 2018-09-10 19:46
I think this is a dupe of #114 

https://github.com/big-neon/bn-api/blob/a34b2060f3c934665711194aa7ed8a8a82fe2c56/api/src/controllers/events.rs#L268

Was added via: https://github.com/big-neon/bn-api/pull/115

**Closed** 2018-09-12 07:49 UTC
Labels: duplicate, to do
