### ISSUE TITLE
Roles - Admin permission does not allow user to add or edit artists in artist database 

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-api#1298] opened 2019-05-28 20:49 UTC
References: https://github.com/big-neon/bigneon/issues/168

Associated issue mentioned how org members could not edit artists. Issue was with the bn-web side as it didn't provide the organization_id which is how we designate if it's an org artist or not. All previous artists were created as public by admins so they are not editable. 

This issue is a stopgap as we have https://github.com/big-neon/bigneon/issues/171 to handle updating the artist flow in the future once we do a deep dive with it. This issue is to set the existing artists as belonging to an organization if they are the only organization using them.

**Comment by nine-tari** [comment] 2019-06-04 00:32
Moved this to in review since the associated PR was merged

**Comment by Anziskavds** [comment] 2019-06-04 09:03
Reviewed and as a Admin I was able to create new artists and edit artist information successfully as expected behaviour. This was on Beta and Develop.

**Comment by Anziskavds** [comment] 2019-06-04 12:25
Tested on Prod and it's working as expected.

https://cl.ly/bfa6e135bcd4

https://cl.ly/1d024241ca84

**Closed by Anziskavds** 2019-06-04 12:25 UTC
Labels: in progress
