### ISSUE TITLE
Adding/editing event and pressing publish button disappears event from API "read" endpoint

### ISSUE THREAD

**Issue by jwietelmann** [big-neon/bn-api#965] opened 2019-01-30 21:17 UTC
I'm not sure if this is a web problem or an API problem. I was logged in as superuser. I tried to create and publish a new event: https://beta.bigneon.com/admin/events/6c233ab3-bd1e-4dad-bcba-a6e48b151005

It shows up in the list of events, but `api/events/<id>` sends back an error of "no results found"

I still needed to be able to test the mobile app against a free ticket, so I tried to add some free tickets to this existing event: https://beta.bigneon.com/admin/events/6c233ab3-bd1e-4dad-bcba-a6e48b151005

After I hit the publish button, it has the same problem.

@zmelamed this is blocking https://github.com/revelrylabs/bn-mobile-react/issues/476 because we need a free ticket to test against.

**Comment by Timo614** [comment] 2019-02-04 21:52
Tried to take a quick look as well just to see if I could reproduce from the tooling but it looks like the associated app has been cleared of data.

I think I may have an idea of what the issue was though from trying things out locally with bn-web.

I see the same behavior locally with an invalid id:
Hitting http://localhost:9000/admin/events/c6c14da9-77e7-4c22-848e-ceb9e81173c1 triggers an API request to http://localhost:9000/organizations/b1bb3ad7-d9ff-4dcd-bf85-5f7ad2a3cc9e/events?past_or_upcoming=c6c14da9-77e7-4c22-848e-ceb9e81173c1

Looks like the reason it's returning no results is that the logic is falling into route that filters the event search:
http://localhost:3000/admin/events/past
http://localhost:3000/admin/events/upcoming

It doesn't look like there's a route in place for displaying the individual event data without the dashboard segment following it (not sure if this framework allows routes to match more specifically so bn-web could fallback on and redirect to the dashboard if it doesn't match past or upcoming @Jasonvdb any clue?):
https://github.com/big-neon/bn-web/blob/61487c646012c9d22a448d61b2928aa5ea194609/src/components/routes/Routes.js#L277..L324

If I append `/dashboard` it does work, however:
http://localhost:3000/admin/events/c6c14da9-77e7-4c22-848e-ceb9e81173c1/dashboard

Not sure if your bug here was related to some oddities with bn-web at the time that have been fixed (the normal flow works for me locally) but I think that explains the error result you were seeing.

I think we may be able to close this one. It may be worth having the admin section redirect to the dashboard for an event if that's possible (although I doubt anyone will hit the URL directly since they'd just use the links so may not be an issue in practice if bn-web's link logic isn't trying to send you there like it may have in this case).

**Comment by Timo614** [comment] 2019-02-04 22:22
Ignore my earlier comment if anyone got a notification: I misunderstood the issue at first thinking that it had to do with the link in the issue (haven't used the API via the beta site previously as well so didn't realize that you could access it that way as a path on the URL). 

It looks like this may be fixed now:
https://beta.bigneon.com/api/events/6c233ab3-bd1e-4dad-bcba-a6e48b151005

Seeing a response hitting the mentioned URL.

**Closed** 2019-02-05 18:25 UTC
Labels: Urgent, bug, current sprint
